apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: friday-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: server
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: friday-java-web-app
  namespace: tap-workload
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "11"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/shatkar-gaig/friday-java-web-app.git
      ref:
        branch: main
